import type { ThemeDefinition } from "./types";
import { createSharedSpectrumRuntime } from "../runtimes/shared-spectrum-runtime";

export const bruiseBloomTheme: ThemeDefinition = {
  id: "bruise-bloom",
  label: "Bruise Bloom",
  category: "indie-emo",
  createRuntime: ({ canvas, controls }) => createSharedSpectrumRuntime(canvas, controls, bruiseBloomTheme),
  palette: {
    fog: 0x04030a,
    ambient: 0x4f456b,
    frontLight: 0xb14567,
    backLight: 0x4b4f8f,
    rimLight: 0xcdd6ff,
    core: 0x09060b,
    coreEmissive: 0x56152e,
    shell: 0x9e8caf,
    ringA: 0xa15371,
    ringB: 0x6d668c,
    ribbon: 0x4b425d,
    tunnel: 0xd6b6d8,
    lineA: 0x8d5b6f,
    lineB: 0x5e5577,
  },
  tuning: {
    fogDensity: 0.082,
    clearHueBase: 0.77,
    clearHueShift: 0.03,
    clearSaturation: 0.2,
    clearLightnessBase: 0.02,
    clearLightnessBloom: 0.025,
    frontLightBase: 1.6,
    frontLightBloom: 2.8,
    frontLightLevel: 4.8,
    backLightBase: 1.2,
    backLightBloom: 2.1,
    backLightHighs: 3.5,
    rimLightBase: 0.6,
    rimLightBloom: 0.9,
    rimLightHighs: 0.8,
    coreEmissiveBase: 0.12,
    coreEmissiveBloom: 0.6,
    coreEmissiveLevel: 1.3,
    coreSaturation: 0.2,
    coreLightnessBase: 0.05,
    coreLightnessLevel: 0.04,
    ringOpacityBase: 0.025,
    ringOpacityLevel: 0.08,
    barOpacityBase: 0.12,
    barOpacityLevel: 0.45,
    barSaturation: 0.45,
    barLightnessBase: 0.26,
    barLightnessLevel: 0.12,
    ribbonOpacityBase: 0.08,
    ribbonOpacityLevel: 0.14,
    ribbonSaturation: 0.32,
    ribbonLightnessBase: 0.22,
    ribbonLightnessLevel: 0.08,
    tunnelOpacityBase: 0.18,
    tunnelOpacityLevel: 0.42,
    tunnelSaturation: 0.48,
    tunnelLightness: 0.58,
    lineOpacityBase: 0.025,
    lineOpacityLevel: 0.12,
  },
};
