import type { ThemeDefinition } from "./types";
import { createSharedSpectrumRuntime } from "../runtimes/shared-spectrum-runtime";

export const glitterTearsTheme: ThemeDefinition = {
  id: "glitter-tears",
  label: "Glitter Tears",
  category: "dream-gaze",
  modes: [
    {
      id: "mist",
      label: "Mist",
    },
    {
      id: "slow-drift",
      label: "Slow Drift",
      overrides: {
        tuning: {
          fogDensity: 0.072,
          clearLightnessBloom: 0.035,
          frontLightLevel: 4.8,
          tunnelOpacityLevel: 0.42,
        },
      },
    },
    {
      id: "starwash",
      label: "Starwash",
      overrides: {
        tuning: {
          clearSaturation: 0.44,
          backLightHighs: 6.8,
          rimLightBloom: 1.8,
          lineOpacityLevel: 0.22,
        },
      },
    },
  ],
  createRuntime: ({ canvas, controls }, theme) => createSharedSpectrumRuntime(canvas, controls, theme),
  palette: {
    fog: 0x090814,
    ambient: 0x5a5e92,
    frontLight: 0xca7ec5,
    backLight: 0x68a7d8,
    rimLight: 0xf4daff,
    core: 0x111123,
    coreEmissive: 0x71446b,
    shell: 0xc5b7ff,
    ringA: 0xd690c7,
    ringB: 0x81a3d8,
    ribbon: 0x6675a6,
    tunnel: 0xf1dcff,
    lineA: 0xe5acd4,
    lineB: 0x99aef0,
  },
  tuning: {
    fogDensity: 0.06,
    clearHueBase: 0.69,
    clearHueShift: 0.06,
    clearSaturation: 0.36,
    clearLightnessBase: 0.04,
    clearLightnessBloom: 0.05,
    frontLightBase: 2.4,
    frontLightBloom: 4,
    frontLightLevel: 6.2,
    backLightBase: 1.9,
    backLightBloom: 3.2,
    backLightHighs: 5.4,
    rimLightBase: 0.9,
    rimLightBloom: 1.3,
    rimLightHighs: 1.2,
    coreEmissiveBase: 0.22,
    coreEmissiveBloom: 0.95,
    coreEmissiveLevel: 1.8,
    coreSaturation: 0.34,
    coreLightnessBase: 0.08,
    coreLightnessLevel: 0.08,
    ringOpacityBase: 0.04,
    ringOpacityLevel: 0.12,
    barOpacityBase: 0.18,
    barOpacityLevel: 0.58,
    barSaturation: 0.62,
    barLightnessBase: 0.34,
    barLightnessLevel: 0.16,
    ribbonOpacityBase: 0.12,
    ribbonOpacityLevel: 0.2,
    ribbonSaturation: 0.48,
    ribbonLightnessBase: 0.34,
    ribbonLightnessLevel: 0.12,
    tunnelOpacityBase: 0.24,
    tunnelOpacityLevel: 0.54,
    tunnelSaturation: 0.72,
    tunnelLightness: 0.72,
    lineOpacityBase: 0.05,
    lineOpacityLevel: 0.16,
    motionSpeed: 0.48,
    motionAmount: 0.58,
  },
};
