import { createProceduralMathRuntime } from "../runtimes/procedural-math-runtime";
import type { ThemeDefinition } from "./types";

export const midnightMathTheme: ThemeDefinition = {
  id: "midnight-math",
  label: "Midnight Math",
  category: "indie-emo",
  modes: [
    {
      id: "embers",
      label: "Embers",
    },
    {
      id: "cathedral",
      label: "Cathedral",
      overrides: {
        tuning: {
          clearLightnessBase: 0.016,
          clearLightnessBloom: 0.018,
          motionSpeed: 0.52,
          motionAmount: 0.74,
          lineOpacityLevel: 0.2,
        },
      },
    },
    {
      id: "sleepless",
      label: "Sleepless",
      overrides: {
        tuning: {
          motionSpeed: 0.96,
          motionAmount: 1.02,
          lineOpacityLevel: 0.24,
          ringOpacityLevel: 0.14,
        },
      },
    },
  ],
  createRuntime: ({ canvas }, theme) => createProceduralMathRuntime(canvas, theme),
  palette: {
    fog: 0x05040b,
    ambient: 0x46385f,
    frontLight: 0xc35d78,
    backLight: 0x5664a1,
    rimLight: 0xf0d7ee,
    core: 0x0b0910,
    coreEmissive: 0x5c2039,
    shell: 0xaa8db8,
    ringA: 0xb86582,
    ringB: 0x7b74a8,
    ribbon: 0x4e4465,
    tunnel: 0xe5c7dd,
    lineA: 0xd48ea8,
    lineB: 0x8c90cb,
  },
  tuning: {
    fogDensity: 0.07,
    clearHueBase: 0.78,
    clearHueShift: 0.03,
    clearSaturation: 0.18,
    clearLightnessBase: 0.022,
    clearLightnessBloom: 0.02,
    frontLightBase: 1.4,
    frontLightBloom: 2,
    frontLightLevel: 3.8,
    backLightBase: 1,
    backLightBloom: 1.6,
    backLightHighs: 2.6,
    rimLightBase: 0.45,
    rimLightBloom: 0.7,
    rimLightHighs: 0.7,
    coreEmissiveBase: 0.1,
    coreEmissiveBloom: 0.4,
    coreEmissiveLevel: 0.9,
    coreSaturation: 0.18,
    coreLightnessBase: 0.05,
    coreLightnessLevel: 0.03,
    ringOpacityBase: 0.03,
    ringOpacityLevel: 0.1,
    barOpacityBase: 0.12,
    barOpacityLevel: 0.4,
    barSaturation: 0.38,
    barLightnessBase: 0.22,
    barLightnessLevel: 0.1,
    ribbonOpacityBase: 0.08,
    ribbonOpacityLevel: 0.12,
    ribbonSaturation: 0.28,
    ribbonLightnessBase: 0.2,
    ribbonLightnessLevel: 0.06,
    tunnelOpacityBase: 0.16,
    tunnelOpacityLevel: 0.3,
    tunnelSaturation: 0.42,
    tunnelLightness: 0.58,
    lineOpacityBase: 0.06,
    lineOpacityLevel: 0.18,
    motionSpeed: 0.74,
    motionAmount: 0.82,
  },
};
