import type { ThemeDefinition } from "./types";
import { createSharedSpectrumRuntime } from "../runtimes/shared-spectrum-runtime";

export const shatterStrobeTheme: ThemeDefinition = {
  id: "shatter-strobe",
  label: "Shatter Strobe",
  category: "club-kaleido",
  modes: [
    {
      id: "burst",
      label: "Burst",
    },
    {
      id: "laser-grid",
      label: "Laser Grid",
      overrides: {
        tuning: {
          ringOpacityLevel: 0.24,
          ribbonOpacityLevel: 0.32,
          tunnelSaturation: 1,
          lineOpacityLevel: 0.28,
        },
      },
    },
    {
      id: "whiteout",
      label: "Whiteout",
      overrides: {
        palette: {
          tunnel: 0xffffff,
          rimLight: 0xffffff,
        },
        tuning: {
          clearLightnessBase: 0.06,
          frontLightBloom: 7.4,
          rimLightBloom: 2.4,
          tunnelLightness: 0.9,
        },
      },
    },
  ],
  createRuntime: ({ canvas, controls }, theme) => createSharedSpectrumRuntime(canvas, controls, theme),
  palette: {
    fog: 0x020308,
    ambient: 0x243464,
    frontLight: 0xff3e8a,
    backLight: 0x2db4ff,
    rimLight: 0xffffff,
    core: 0x05070f,
    coreEmissive: 0x9d1d75,
    shell: 0x7bd6ff,
    ringA: 0xff5ea6,
    ringB: 0x56b6ff,
    ribbon: 0x355fbc,
    tunnel: 0xf4fbff,
    lineA: 0xff7ec2,
    lineB: 0x88ccff,
  },
  tuning: {
    fogDensity: 0.05,
    clearHueBase: 0.62,
    clearHueShift: 0.14,
    clearSaturation: 0.52,
    clearLightnessBase: 0.03,
    clearLightnessBloom: 0.06,
    frontLightBase: 3.5,
    frontLightBloom: 6,
    frontLightLevel: 8.5,
    backLightBase: 3,
    backLightBloom: 4.5,
    backLightHighs: 7.2,
    rimLightBase: 1.1,
    rimLightBloom: 1.6,
    rimLightHighs: 1.5,
    coreEmissiveBase: 0.34,
    coreEmissiveBloom: 1.3,
    coreEmissiveLevel: 2.4,
    coreSaturation: 0.48,
    coreLightnessBase: 0.08,
    coreLightnessLevel: 0.1,
    ringOpacityBase: 0.06,
    ringOpacityLevel: 0.16,
    barOpacityBase: 0.22,
    barOpacityLevel: 0.68,
    barSaturation: 0.82,
    barLightnessBase: 0.4,
    barLightnessLevel: 0.2,
    ribbonOpacityBase: 0.14,
    ribbonOpacityLevel: 0.24,
    ribbonSaturation: 0.7,
    ribbonLightnessBase: 0.42,
    ribbonLightnessLevel: 0.14,
    tunnelOpacityBase: 0.3,
    tunnelOpacityLevel: 0.62,
    tunnelSaturation: 0.92,
    tunnelLightness: 0.78,
    lineOpacityBase: 0.06,
    lineOpacityLevel: 0.22,
    motionSpeed: 1.28,
    motionAmount: 1.18,
  },
};
